[package]
name = "elfie-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "elfie"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
elfie = { path = "..", version = "0.1.0" }
env_logger = "0.11.6"
fs-err = "3.1.0"
