[package]
name = "elb-dl"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default =  ["glibc", "musl"]
glibc = ["dep:glob"]
musl = []

[dependencies]
elb = { path = "..", version = "0.1.0" }
fs-err = "3.1.0"
glob = { version = "0.3.2", optional = true }
log.workspace = true
thiserror.workspace = true

[dev-dependencies]
base32 = "0.5.1"
sha2 = "0.10.8"
tempfile = "3.18.0"
walkdir = "2.5.0"
env_logger = "0.11.6"

[lints]
workspace = true
