---
name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    env:
      TZ: Europe/Berlin
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Test
        run: ./ci/test.sh
      - name: Install cargo-cross
        run: cargo install cross
      - name: Cross test
        run: ./ci/cross.sh
      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: ./ci/publish.sh
